### ISSUE TITLE
Support to customize executed SQL

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aws-sam-rds-initialize-user#5]
* https://golang.org/pkg/text/template/
* http://masterminds.github.io/sprig/

```yaml
sqls:
- CREATE ROLE foo WITH LOGIN PASSWORD '{{.Password.foo}}'
- ALTER DATABASE {{.DBName}} OWNER TO foo
passwords:
- foo
```

```yaml
sql: |
  {{$DBName := .DBName -}}
  {{range .Password -}}
  CREATE ROLE {{.Name}} WITH LOGIN PASSWORD '{{.Value}}';
  ALTER DATABASE {{$DBName}} OWNER TO {{.Name}};
  {{end -}}
passwords:
- foo
params:
- name:
  value:
```

**Comment by suzuki-shunsuke** [comment]
How to support placeholders 🤔

**Comment by suzuki-shunsuke** [comment]
## Tengo

```yaml
sql: |
  results := [
    {
      query: "",
      args: [],
    }
  ]
passwords:
- foo
params:
- name:
  value:
```
