### ISSUE TITLE
Support to customize Secret format

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aws-sam-rds-initialize-user#7]
```yaml
secrets:
- name:
  value: |
    username: foo
    password: "{{.Password}}"
```
